# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  deploy-cloudflare:
    runs-on: ubuntu-latest
    needs: publish-npm
    env:
      CLOUDFLARE_PROJECT_NAME: bbox-skeleton-demo
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Inject .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN_INSTALL}}" > ~/.npmrc
      - name: Install dependencies for playground
        run: npm install
        working-directory: playground
      - name: Install latest bbox-skeleton
        run: npm install bbox-skeleton@latest
        working-directory: playground
      - name: Remove .npmrc
        run: rm ~/.npmrc
      - name: test installed version
        run: cat package.json | grep -e '"bbox-skeleton":'
        working-directory: playground
      # - name: Install wrangler
      #   run: npm install --save-dev wrangler@latest
      #   working-directory: playground
      - name: Build playground
        run: npm run build
        working-directory: playground
      - name: Deploy to Cloudflare Pages
        run: npx wrangler pages deploy dist --project-name ${{ env.CLOUDFLARE_PROJECT_NAME }} --branch main
        working-directory: playground